import {type ViewerDashboardResponse, viewerDashboardResponseSchema} from "@/schemas/dashboard.ts";
import {API_URL, getAuthorizationHeaders, getErrorMessage} from "@/api/config.ts";

/**
 * Retrieves the viewer dashboard metrics from the backend.
 *
 * The function sends an authenticated GET request to the viewer dashboard
 * endpoint using the authorization headers generated by
 * `getAuthorizationHeaders()`.
 *
 * If the request is unsuccessful, the backend response is processed by
 * `getErrorMessage()` to retrieve a meaningful error description, which is
 * then thrown as a JavaScript Error.
 *
 * On a successful request, the response body is parsed as JSON and validated
 * against `viewerDashboardResponseSchema`. This ensures that the data received
 * from the backend matches the expected dashboard response structure before
 * it is returned to the application.
 *
 * @returns A Promise that resolves to a validated `ViewerDashboardResponse`
 * containing the viewer dashboard metrics and infrastructure statistics.
 *
 * @throws {Error} Throws an error if the HTTP request is unsuccessful.
 */
export async function getViewerDashboard():
    Promise<ViewerDashboardResponse> {
    const response = await fetch(
        `${API_URL}/dashboard/viewer`,
        {
            method: "GET",
            headers: getAuthorizationHeaders(),
        }
    );

    if (!response.ok) {
        throw new Error(
            await getErrorMessage(
                response,
                "Failed to retrieve dashboard metrics."
            )
        );
    }

    // Treat the external API response as unknown until it has
    // been validated against the expected Zod schema.
    const data: unknown =
        await response.json();

    // Validate the backend response and return the resulting
    // type-safe dashboard data.
    return viewerDashboardResponseSchema.parse(
        data
    );
}